matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - g++-6
            - libpthread-stubs0-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

language: cpp

script: g++-6 -std=c++14 -lpthread *.cpp

